[package]
name = "next-taskless"
version = "0.0.1"
description = "TBD"
license = "MIT"
edition = "2024"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
turbo-unix-path = { workspace = true }
